version: '2'

services:
  influxdb:
    image: influxdb
    restart: always
    environment:
      INFLUXDB_DB: "sensor_data"
      INFLUXDB_USER: "rpi"
      INFLUXDB_USER_PASSWORD: "rpi"
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana
    restart: always
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
  python:
    build: .
    privileged: true
    environment:
      INTERVAL: 180
    restart: always
    depends_on:
      - grafana

volumes:
  influxdb_data:
  grafana-storage: