version: '2'

services:
  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
  influxdb:
    image: influxdb
    environment:
      INFLUXDB_DB: "sensor_data"
      INFLUXDB_USER: "rpi"
      INFLUXDB_USER_PASSWORD: "rpi"
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
    - "8086:8086"

volumes:
  influxdb_data: